name: 📦 Create Version PR

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm ci

      - name: Create Version Pull Request
        uses: changesets/action@v1
        with:
          publish: false
          title: "chore: 🔖 version bump"
          commit: "chore: release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
